brush/package-lock.json, brush/src/components/Content.js, brush/src/components/InputROM.js, brush/src/components/InputROMModal.js
Some UI improvements.
Now the main page asks for the ROM file in a modal component, which disappears after the ROM file is uploaded.
=> brush: add modal to input ROM file

README.md
The project uses docker in order to compile the webassembly code.
This commit adds a warning on the readme for those who may not have
docker installed yet. It also adds an installation guide from docker.com
Fixes issue #5.
=> doc: add docker installation guide on readme

brush/src/providers/ROMProvider.js
At `useROMBuffer` provider, we need a `useEffect` to try to fetch the ROM at localStorage. We need to do it only once, but it is run every time.
To fix it, following [this answers](https://stackoverflow.com/a/53121021/3440266), we need to use `[]` to run `useEffect` only once.
Resolves https://github.com/macabeus/klo-gba.js/issues/16
=> brush: fix ROMProvider to run useEffect only once

brush/src/components/Body.js, brush/src/components/map/index.js, brush/src/hooks/useWhenVisionChanges.js
Now when the user changes the vision, MapFooter message and HighlightCoordinates will be erase.
To do it, was add a new custom hook, `useWhenVisionChanges`.
=> brush: add auto erase for MapFooter message and HighlightCoordinates

brush/src/.stylelintrc, brush/src/components/Body.js, brush/src/components/MapEmptyState/index.js, brush/src/components/MapEmptyState/style.css, brush/src/providers/VisionProvider.js
Add `MapEmptyState` using the drawing made by @Kniksisk (see PR #21).
Resolves https://github.com/macabeus/klo-gba.js/issues/9
=> Add map empty state

brush/src/components/Body.js, brush/src/components/MapActionsBar/SaveButton.js, brush/src/components/MapActionsBar/SwitchTool.js, brush/src/components/TileSet/index.js, brush/src/components/TileSet/style.css, brush/src/components/map/DrawingLayer/index.js, brush/src/components/map/TilemapLayer/index.js, brush/src/components/map/global-state.js, brush/src/components/map/index.js, brush/src/components/map/point/PointTile.js, brush/src/constants/tileNameToColor.js, brush/src/hooks/useTool.js, brush/src/providers/VisionProvider.js, scissors/src/from-scheme-get-tile-name-by-id.js, scissors/src/get-vision.js, scissors/src/huffman.js, scissors/src/index.js, scissors/src/lzss.js, scissors/src/vision-manager.js, scissors/src/wasm/huffman.c, scissors/src/wasm/lzss.c
Now, finally we can create own vision editing a tilemap and save it on the ROM to play it!
This PR is very huge (sorry about that), adding many things in order to do it be possible:
- some refactors important to the new commits on this PR
- add component `TileSet` which user can use it to select the tile that wants to paint
- add component `SwitchTool` which user can use it to switch between the tools `magnifying glass` and `brush`
- add wrappers to functions from C code: `LZS_Encode` and `HUF_Encode`. These functions is important to compress the new tilemap and save it on ROM, that is make by `saveVision` function
=> Add feature to edit the tilemap and save it on the ROM

README.md, brush/config/webpack.config.js, brush/package-lock.json, brush/package.json, scissors/src/huffman.js, scissors/src/lzss.js
Resolves https://github.com/macabeus/klo-gba.js/issues/29
Using `gh-pages` package, adds a build process to deploy at GitHub Pages.
Currently Brush are getting wasm files from `node_modules/scissors/dist` folder, but the deploy didn't send the `node_modules` folder to GitHub Pages, then to fix it this PR adds the wasm files to `static/wasm` folder and updates the path to Brush to get these wasm files.
=> Add static web page build

brush/package-lock.json, brush/package.json, brush/src/components/InputRom/InputRomButton.js, brush/src/components/InputRom/style.css, brush/src/errors/romRegioNotSupported.js, scissors/package-lock.json, scissors/package.json, scissors/src/index.js, scissors/src/romRegion.js
Closes https://github.com/macabeus/klo-gba.js/issues/36
This PR adds an alert when the user is trying to upload a ROM that isn't not supported.
To do it, `scissors` now calculates the hash of the ROM and check if it `usa` or not.
=> rom-load: add error if trying to load a non supported rom region

brush/src/components/MapActionsBar/SaveButton.js
Some emulator only can open ".gba" files
=> save-button: fix default filename extension

brush/src/components/TileSet/index.js
We had some problem with without red, like `0x007D00`
=> Fix tile set colors

brush/src/components/SelectVision/index.js, scissors/src/index.js, scissors/src/visionManager.js, scissors/src/visions/1-1.js, scissors/src/visions/1-2.js, scissors/src/visions/1-3.js, scissors/src/visions/index.js
Small UI improvement to display the world name at `SelectionVision` component.
Also, the code has been improved removing some eslint disabled rules.
=> [SelectionVision] Display world name

scissors/src/rom.js, scissors/src/visionManager.js, scissors/src/visions/1-1.js, scissors/src/visions/1-2.js, scissors/src/visions/1-3.js
Closes https://github.com/macabeus/klo-gba.js/issues/34
The approach to resolve this bug was to patch the original code to load the visions.
Instead of loading the tilemap at the original address, we redirect it to load the tilemap in another memory region that now we are using to save the custom tilemaps.
=> [vision-manager] N-ary vision crashes when saving a tilemap for vision N-1

brush/src/components/Map/DrawingLayer/index.js, brush/src/components/MapActionsBar/SwitchTool.js, brush/src/hooks/useTool.js
Rename the tool `magnifying glass` to `inspector`, that is a more expressive one
=> [Tools] Rename "magnifying glass" to "inspector"

brush/src/components/Map/index.js, brush/src/components/Map/style.css
This PR fixes #14.
I used a div to wrap the Pixi's Stage component and set auto-scrolling.
Setting scroll options on the canvas or the map card didn't work as intended.
=> tilemap: fix overflow

brush/src/components/KloGbaSidebar/DisplayMapOptions/index.js, brush/src/components/Map/HighlightCoordinates/index.js, brush/src/components/Map/ObjectsLayer/index.js, brush/src/components/Map/Point/PointObject.js, brush/src/components/Map/index.js, brush/src/components/MapActionsBar/SaveButton.js, brush/src/components/ObjectsTable/index.js, brush/src/pages/Main/LoadedRom.js, brush/src/providers/DisplayMapOptionsProvider.js, brush/src/providers/VisionProvider.js, scissors/src/index.js, scissors/src/objectMaps.js, scissors/src/visionManager.js, scissors/src/visions/1-1.js, scissors/src/visions/1-2.js, scissors/src/visions/1-3.js
Rename `OAM` to `Object`.
Initially I named it was `OAM` in order to not confuse with JS' objects, but it was a bad decision, because `OAM` is the abbreviation for `Object Attribute Memory`... a region of memory on Gameboy Advance, not a specific object on the game.
=> objects: refac renaming oam -> object

scissors/src/rom.js, scissors/src/visionManager.js, scissors/src/visions/1-1.js, scissors/src/visions/1-2.js, scissors/src/visions/1-3.js
This value is unnecessary, because the uncompress algorithm can infer when the blob ends.
Removing it became easier to write the file vision.
=> visions: remove end address for tilemaps

brush/src/components/KloGbaSidebar/Hacks/index.js, brush/src/components/KloGbaSidebar/Hacks/style.css, brush/src/components/KloGbaSidebar/index.js, react-gbajs/src/emulator/gba.js, react-gbajs/src/react/gba-provider.js
Add hacks feature on `react-gbajs`, and options to turn on it.
=> react-gbajs: add hacks

brush/package.json, brush/src/components/Emulator/index.js, brush/src/hooks/useGbaSaveRestoreState.js, brush/src/providers/VisionProvider.js, yarn.lock
Bump `react-gbajs` to 1.0.0: https://github.com/macabeus/react-gbajs/releases/tag/1.0.0
=> chore: bump react-gbajs to 1.0.0

README.md, brush/src/components/Map/TilemapLayer/index.js, brush/src/components/Map/index.js, brush/src/providers/VisionProvider.js, scissors/src/visionManager.js, scissors/src/visions/infos/1-1.js, scissors/src/visions/infos/1-2.js, scissors/src/visions/infos/1-3.js, scissors/src/visions/infos/1-5.js, scissors/src/visions/infos/template.js
=> Automate the tilemap size fetch

brush/src/components/Map/DrawingLayer/index.js, brush/src/components/Map/ObjectsLayer/index.js
Three small improvements:
- if selects a blank tile using the eyedropper tool, the active tool will be the eraser instead of the brush
- add a square cursor when hovering the drawing layer
- fix bug when react cached an object component from the previous selected vision
=> Small improvements
