macabeus/klo-gba.js

- README.md
This PR fixes the problem related on issue #4.
> doc: fix compile wasm command

- brush/package-lock.json
- brush/package.json
- brush/src/components/Content.js
- brush/src/components/SelectVision.js
- brush/src/providers/ROMProvider.js
Is a very boring task always need browse at the file system the ROM file to load it.
Then this PR adds an auto load of a previous loaded ROM.
> brush: add save and auto load rom using IndexedDB

- brush/package-lock.json
- brush/package.json
- brush/src/components/Body.js
- brush/src/components/ObjectsTable.js
- brush/src/components/map/HighlightCoordinates/index.js
- brush/src/components/map/index.js
- brush/src/components/map/point/PointOam.js
- brush/src/index.js
- scissors/package-lock.json
- scissors/package.json
- scissors/src/get-vision.js
- scissors/src/index.js
- scissors/src/oam-maps.js
Add two new components, `ObjectsTable` and `HighlightCoordinates`.
The first component is used to list the Objects from OAM. When the user click on a row, highlight this object on the `Map` using the component `HighlightCoordinates`.
Also, this PR do some refactors to isolate better the responsibilities between `brush` and `scissors`. It is useful to create the `ObjectsTable` component.
> Add ObjectsTable

- brush/src/components/map/OAMLayer/index.js
- brush/src/components/map/TilemapLayer/index.js
- brush/src/components/map/index.js
- brush/src/providers/VisionProvider.js
Refactor `Map` componente splitting in into `TilemapLayer` and `OAMLayer`.
Improving performance for `TilemapLayer` using memorization
> Refactor and improve performance for Map component

- brush/src/components/Body.js
- brush/src/components/map/GridLayer/index.js
- brush/src/components/map/HighlightCoordinates/index.js
- brush/src/components/map/index.js
Add a button to user can change the map display with two options:
- show/hide grid
- show/hide OAM
Then, was add a new component called `GridLayer`.
> Add map display options

- brush/src/components/Map/DrawingLayer/index.js
- brush/src/components/Map/TilemapLayer/index.js
- brush/src/components/MapActionsBar/SwitchTool.js
- brush/src/components/TileSet/index.js
- scissors/src/fromSchemeGetTileNameById.js
Add the eraser tool and remove the empty tile on `TileSet`.
> Add Eraser tool

- brush/src/components/SelectVision/index.js
resolves https://github.com/macabeus/klo-gba.js/issues/10
> select-vision: fix state when none vision is selected

- brush/config/webpack.config.js
- brush/src/index.html
The icon was not display on website built, because I forgot to change the webpack script
> icon: fix display on built website

- brush/src/components/Map/DrawingLayer/index.js
- brush/src/components/Map/index.js
- brush/src/components/ZoomSelector/index.js
- brush/src/pages/Main/LoadedRom.js
Add resolution option on tilemap and `ZoomSelector` component to update it
> Add resolution option

- brush/src/components/DisplayMapOptions/index.js
- brush/src/components/MapActionsBar/SaveButton.js
- brush/src/pages/Main/LoadedRom.js
Disable the save tilemap button when none vision is selected.
> Disable the save button

- brush/src/components/ChangeRom/index.js
- brush/src/pages/Main/LoadedRom.js
- brush/src/providers/ROMProvider.js
- brush/src/providers/VisionProvider.js
- scissors/src/rom.js
- scissors/src/romRegion.js
- scissors/src/visionManager.js
- scissors/src/visions/1-1.js
- scissors/src/visions/1-2.js
- scissors/src/visions/1-3.js
If there is a custom tilemap, load it instead of the default tilemap.
Also, adds a button to load another ROM.
> Allow to load custom ROM and custom tilemap

- brush/src/components/Map/OAMLayer/index.js
- brush/src/components/Map/Point/PointOam.js
- brush/src/components/Map/Point/getScaledCoordinates.js
- brush/src/components/Map/Point/index.js
- brush/src/components/Map/Point/withDraggable.js
- brush/src/components/Map/index.js
- brush/src/components/MapActionsBar/SaveButton.js
- brush/src/providers/VisionProvider.js
- scissors/src/rom.js
- scissors/src/splitHexValueIntoBytesArray.js
- scissors/src/visionManager.js
Finally is possible to move an OAM around the map! And save the new positions of the OAM, of course.
> Add move OAM feature

- brush/src/components/Map/DrawingLayer/index.js
- brush/src/components/Map/index.js
(Probably) fix https://github.com/macabeus/klo-gba.js/issues/73
https://github.com/inlet/react-pixi/issues/150
> map: fix bug when try to dragging an object when update the zoom

- brush/src/components/KloGbaSidebar/DisplayMapOptions/ZoomSelector.js
- brush/src/constants/zoomValues.js
- brush/src/providers/DisplayMapOptionsProvider.js
Refac code about zoom, and change default zoom
> Improve zoom

- brush/src/components/InputRom/InputRomButton.js
- brush/src/components/InputRom/index.js
- brush/src/components/KloGbaSidebar/ChangeRom/index.js
- brush/src/components/KloGbaSidebar/SelectVision/index.js
- brush/src/pages/Main/index.js
- brush/src/providers/ROMProvider.js
Add a cancel button on modal to upload a new ROM.
> Cancel upload of a new rom

- brush/src/components/ClearHighlightCoordinates/index.js
- brush/src/components/Map/ObjectsLayer/index.js
- brush/src/components/Map/Point/PointObject.js
- brush/src/components/Map/Point/index.js
- brush/src/components/Map/Point/withDraggable.js
- brush/src/components/Map/index.js
- brush/src/components/ObjectDetail/Coordinates.js
- brush/src/components/ObjectDetail/Kind.js
- brush/src/components/ObjectDetail/index.js
- brush/src/components/ObjectDetail/style.css
- brush/src/hooks/useForceUpdate.js
- brush/src/pages/Main/LoadedRom.js
- brush/src/pages/Main/style.css
- brush/src/providers/VisionProvider.js
- scissors/src/objectMaps.js
- scissors/src/visionManager.js
Add the new card `ObjectDetsils` to be able to change the object's kind and to expose others informations of that.
> Add ObjectDetails card

- brush/src/components/Map/DrawingLayer/index.js
- brush/src/components/Map/index.js
- brush/src/components/MapActionsBar/SwitchTool.js
- brush/src/hooks/useTool.js
- brush/src/pages/Main/LoadedRom.js
Resolves https://github.com/macabeus/klo-gba.js/issues/74
> Add eyedropper

- brush/src/components/MapActionsBar/SwitchTool.js
- brush/src/components/MapEmptyState/index.js
- brush/src/hooks/useToolKeyboardShortcut.js
> tools: add shortcut to switch between tools by keyboard

- brush/src/components/EmulatorUpdateVision/index.js
- brush/src/components/KloGbaSidebar/DisplayMapOptions/style.css
- brush/src/components/Map/DrawingLayer/index.js
- brush/src/components/Map/Point/PointObject.js
- brush/src/components/MapEmptyState/index.js
- brush/src/index.html
- brush/src/pages/Main/style.css
- scissors/src/objectMaps.js
This PR add many small improvements around the project:
- rename the page title to `klo-gba.js`
- add keyboard shortcut to update the vision on emulator
- fix some css warnings
- show id of object and tile in hex on `MapFooter`
- improve arrow character at name of flying moo
> Add small improvements

- brush/src/components/InputRom/InputRomButton.js
- brush/src/components/InputRom/index.js
- brush/src/errors/romInvalidExtension.js
> input-rom: improve instructions

- shellscript/compile-webassembly.sh
Fix this bug: https://github.com/macabeus/klo-gba.js/discussions/94#discussioncomment-565030
> shellscript: set specific image version

- brush/src/components/InputRom/index.js
- brush/src/index.html
Two small improvements:
- input-rom: links open in a new tab
- brush: add `<meta name="description">`
> Small improvements

- brush/src/components/KloGbaSidebar/Community/index.js
- brush/src/components/KloGbaSidebar/Community/style.css
- brush/src/components/KloGbaSidebar/style.css
Add a `z-index` on the community container to can click on its icons even when modal is present.
> klo-gba-sidebar: can click on community icons when modal is present
